name: genburav
channels:
- conda-forge
- nodefaults
dependencies:
- python >=3.9,<3.13
- pip
- pip:
  - torch>=2.5.1
  - torchvision>=0.20.1
  - torchaudio>=2.5.1
  - omegaconf>=2.3.0, <3
  - timm>=1.0.12, <2
  - matplotlib>=3.10.0, <4
  - lmdb>=1.6.2, <2
  - scikit-learn>=1.6.0, <2
  - chamferdist>=1.0.3, <2
  - pytorch-fid>=0.3.0, <0.4
  - tensorboard>=2.18.0, <3
