name: genburav
channels:
- conda-forge
- nodefaults
dependencies:
- python >=3.9,<3.13
- cxx-compiler <1.8
- pip
- pip:
  - torch<2.6
  - torchvision<0.21
  - torchaudio<2.6
  - omegaconf>=2.3.0, <3
  - timm>=1.0.12, <2
  - matplotlib>=3.10.0, <4
  - lmdb>=1.6.2, <2
  - scikit-learn>=1.6.0, <2
  - chamferdist>=1.0.3, <2
  - tensorboard>=2.18.0, <3
  - plyfile>=1.1, <2
  - ./submodules/simple-knn
  - ./submodules/diff-gaussian-rasterization
