[project]
channels = ["conda-forge"]
name = "genburav"
platforms = ["linux-64"]

[tasks]
train = {cmd = "python run.py train"}
test = {cmd = "python run.py test"}
infer = {cmd = "python run.py infer"}

[system-requirements]
cuda = "12"

[dependencies]
python = ">=3.9,<3.13"

[pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu124" }
torchaudio = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu124" }
omegaconf = ">=2.3.0, <3"
timm = ">=1.0.12, <2"
matplotlib = ">=3.10.0, <4"
lmdb = ">=1.6.2, <2"
scikit-learn = ">=1.6.0, <2"
chamferdist = ">=1.0.3, <2"
tensorboard = ">=2.18.0, <3"

[pypi-options]
no-build-isolation = ["chamferdist", "pytorch-fid"]
