num_classes: 100
model:
  type: ResNet_CIFAR
  block: BasicBlock
  layers: [3, 4, 6, 3]
  num_classes: ${num_classes}
dataset_type: CIFAR100
train_transforms:
- type: RandomCrop
  size: 32
  padding: 4
- type: RandomHorizontalFlip
  p: 0.5
val_transforms: []
collate_keys: [img, gt_label]
data_preprocessor:
  type: ImgClsDataPreprocessor
  minmax: false
  mean: [129.304, 124.070, 112.434]
  std: [68.170, 65.392, 70.418]
  batch_aug:
    type: RandMixUpCutMix
    num_classes: ${num_classes}
    switch_prob: 0.5
    alpha_mixup: 1.0
    alpha_cutmix: 1.0
  num_classes: ${num_classes}
data_root: data/cifar100
train_dataloader:
  batch_size: 256
  num_workers: 4
  sampler:
    type: DistributedEvalSampler
    shuffle: true
  collate_keys: ${collate_keys}
  dataset:
    type: ${dataset_type}
    data_root: ${data_root}
    transforms: ${train_transforms}
    test_mode: false
val_dataloader:
  batch_size: 1024
  num_workers: 4
  sampler:
    type: DistributedSampler
    shuffle: false
  collate_keys:
  - img
  - gt_label
  dataset:
    type: ${dataset_type}
    data_root: ${data_root}
    transforms: ${val_transforms}
    test_mode: true
evaluator:
  type: Evaluator
  metrics:
  - type: Accuracy
    topk: [1, 5]
train_epochs: 200
optimizer:
  type: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
scheduler:
  type: CosineLR
  t_initial: ${train_epochs}
  lr_min: 1.0e-06
  t_in_epochs: true
visualizer:
  type: ImgClsVisualizer
  use_tensorboard: true
seed: 0
use_amp: true