#python run.py train --devs 0 --cfg configs/simddpm_swrissroll.yaml --log_freq 1
model:
  type: SimDDPM
  in_channels: 2
  num_steps: 100
dataset_type: SwissRoll
collate_keys: [gt]
data_preprocessor:
  type: VecDataPreprocessor
train_dataloader:
  batch_size: 128
  sampler:
    type: DistributedSampler
    shuffle: true
  collate_keys: ${collate_keys}
  dataset:
    type: ${dataset_type}
    test_mode: false
val_dataloader:
  batch_size: 10000
  sampler:
    type: DistributedEvalSampler
    shuffle: false
  collate_keys: ${collate_keys}
  dataset:
    type: ${dataset_type}
    test_mode: true
evaluator:
  type: Evaluator
  metrics:
  - type: ChamferDistance
  intervals: 100
train_epochs: 2000
optimizer:
  type: Adam
  lr: 1.0e-3
visualizer:
  type: VecDiffusionVisualizer
  use_tensorboard: true
seed: 0
use_amp: false
ckpt_interval: ${train_epochs}