num_classes: 10
model:
  type: SimNet
  num_classes: ${num_classes}
dataset_type: CIFAR10
train_transforms:
- type: RandomCrop
  size: 32
  padding: 4
- type: RandomHorizontalFlip
  p: 0.5
val_transforms: []
collate_keys: [img, gt_label]
data_preprocessor:
  type: ImgDataPreprocessor
  minmax: false
  mean: [129.304, 124.070, 112.434]
  std: [68.170, 65.392, 70.418]
  batch_aug:
    type: RandMixUpCutMix
    num_classes: ${num_classes}
    switch_prob: 0.5
    alpha_mixup: 1.0
    alpha_cutmix: 1.0
  num_classes: ${num_classes}
data_root: data/cifar10
train_dataloader:
  batch_size: 512
  num_workers: 4
  sampler:
    type: DistributedSampler
    shuffle: true
  collate_keys: ${collate_keys}
  dataset:
    type: ${dataset_type}
    data_root: ${data_root}
    transforms: ${train_transforms}
    test_mode: false
val_dataloader:
  batch_size: 1024
  num_workers: 4
  sampler:
    type: DistributedSampler
    shuffle: false
  collate_keys: ${collate_keys}
  dataset:
    type: ${dataset_type}
    data_root: ${data_root}
    transforms: ${val_transforms}
    test_mode: true
evaluator:
  type: Evaluator
  metrics:
  - type: Accuracy
    topk: [1, 5]
train_epochs: 50
optimizer:
  type: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 1.0e-4
scheduler:
  type: CosineLR
  t_initial: ${train_epochs}
  lr_min: 1.0e-6
  t_in_epochs: true
seed: 0
use_amp: true