model:
  type: VQVAE
  in_channels: 3
  sampling_hidden_dim: 128
  res_hidden_dim: 32
  num_sampling: 2
  num_res_block: 2
  embedding_dim: 64
  num_embedding: 512
  use_ema: true
  ema_decay: 0.99
dataset_type: CIFAR10
collate_keys: [img]
data_preprocessor:
  type: ImgDataPreprocessor
  minmax: false
  mean: [125.307, 122.950, 113.865]
  std: [62.993, 62.089, 66.705]
data_root: data/cifar10
train_dataloader:
  batch_size: 32
  sampler:
    type: DistributedSampler
    shuffle: true
  collate_keys: ${collate_keys}
  dataset:
    type: ${dataset_type}
    data_root: ${data_root}
    test_mode: false
val_dataloader:
  batch_size: 1024
  sampler:
    type: DistributedEvalSampler
    shuffle: false
  collate_keys: ${collate_keys}
  dataset:
    type: ${dataset_type}
    data_root: ${data_root}
    test_mode: true
train_epochs: 7
evaluator:
  type: Evaluator
  metrics:
  - type: PeakSignalNoiseRatio
  - type: FrechetInceptionDistance
    batch_size: 512
  intervals: [1, "${train_epochs}"]
optimizer:
  type: Adam
  lr: 3.0e-4
scheduler:
  type: CosineLR
  t_initial: ${train_epochs}
  lr_min: 1.0e-5
  t_in_epochs: true
visualizer:
  type: ImgVisualizer
  use_tensorboard: true
seed: 0
use_amp: false
ckpt_interval: ${train_epochs}